### ISSUE TITLE
Effectively clean-up cache to reduce layer sizes in Docker

### ISSUE THREAD

**Issue by CramBL** [luftkode/qemu_packer#2]
Each instance of 'RUN' creates another layer, all caching done in a 'RUN' is saved in a layer, but never used by Docker so it just bloats the layer.

Unfortunately you cannot make a catch-all clean up like this:
https://github.com/luftkode/qemu_packer/blob/3c5e70f862e24b83cd22dc4974f863d511154d87/Dockerfile#L15C76-L15C76

You have to clean up cache in each layer. 

### When installing with Pip
When installing with pip, cleanup by adding the  `--no-cache-dir` flag, like: `pip install --no-cache-dir matplotlib` it is necessary to add the flag to every `pip install` invocation. More information: https://hub.docker.com/_/python/

### With apt
Don't use apt, it is not for production, use 'apt-get'. Finish with a layer with:

```shell
&& apt-get clean \
    && rm -rf /var/lib/apt/lists/*
```
More information: https://docs.docker.com/develop/develop-images/instructions/

This apt-get cleanup will have less of an effect on ubuntu images as they have a hack that attempts to do the same as `apt-get clean` (They do this: https://github.com/moby/moby/blob/03e2923e42446dbb830c654d0eec323a0b4ef02a/contrib/mkimage/debootstrap#L82-L105)

**Comment by gregerspoulsen** [comment]
Thanks a lot for your input - I've tried to incorporate your suggestions in #3.
